from afterpay.exceptions.afterpay_error import AfterpayError

class UnexpectedError(AfterpayError):
    """
    Unexpected error
    """
    pass
